<a href="https://colab.research.google.com/github/borzX/Py_hw9/blob/main/Py_hw9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задача 40: Работать с файлом california_housing_train.csv, который находится в папке sample_data. Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population).

Задача 42: Узнать какая максимальная households в зоне минимального значения population.

In [4]:
import pandas as pd

In [6]:
df = pd.read_csv('sample_data/california_housing_train.csv')

In [13]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

Задача 40: Работать с файлом california_housing_train.csv, который находится в папке sample_data. Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population).

In [19]:
df.loc[df['population']>500, ['population', 'median_house_value']]

       population  median_house_value
0          1015.0             66900.0
1          1129.0             80100.0
3           515.0             73400.0
4           624.0             65500.0
5           671.0             74000.0
...           ...                 ...
16995       907.0            111400.0
16996      1194.0             79000.0
16997      1244.0            103600.0
16998      1298.0             85800.0
16999       806.0             94600.0

[15395 rows x 2 columns]

Задача 42: Узнать какая максимальная households в зоне минимального значения population.

In [35]:
min_population = df.population.min()
df[df['population'] == min_population].households.max()

4.0